// Copyright 2026 Summon Software Labs
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Example 01: the thermal state of a single zone.
//
// One declared zone, one fresh observation, one evaluation. The point of the
// example is the shape of the answer: a known headroom, a known band, an exact
// power margin and an emitted placement constraint that is advice only.
//
// The observation is generated by this harness (provenance synthetic_harness).
// No real hardware is exercised and no real sensor is read.

#include <thermal_zone_manager/thermal_zone_manager.hpp>

#include <cstdint>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace tzm = thermal_zone_manager;

namespace {

constexpr std::int64_t kClockStartNs = 1700000000000000000LL;  // 2023-11-14T22:13:20Z
constexpr std::int64_t kFloorMc = 15000;
constexpr std::int64_t kDerateOnsetMc = 70000;
constexpr std::int64_t kCeilingMc = 90000;
constexpr std::int64_t kCriticalMc = 100000;
constexpr std::int64_t kResistanceUkw = 400000;
constexpr std::int64_t kDeclaredHeatMw = 2000;
constexpr std::int64_t kObservedMc = 55000;  // 55.000 C
constexpr std::int64_t kValidityNs = 60000000000LL;

std::string format_celsius(std::int64_t value) { return tzm::format_milli(value) + " C"; }
std::string format_watts(std::int64_t value) { return tzm::format_milli(value) + " W"; }

}  // namespace

int main() {
  tzm::ManualClock clock{tzm::Timestamp{kClockStartNs}};

  tzm::EngineOptions options;
  options.actor = tzm::ActorId::literal("tzm-example-01");
  options.clock = &clock;

  tzm::Result<std::unique_ptr<tzm::ThermalZoneEngine>> opened = tzm::ThermalZoneEngine::open(options);
  if (!opened.ok()) {
    std::cerr << opened.error().to_string() << "\n";
    return 1;
  }
  const std::unique_ptr<tzm::ThermalZoneEngine> engine = std::move(opened.value());

  // A fresh engine carries control-plane epoch zero, which authorises nothing.
  tzm::EpochRequest epoch_request;
  epoch_request.command = tzm::CommandId::first();
  epoch_request.attempt = tzm::AttemptId::first();
  epoch_request.expected_current = tzm::ControlPlaneEpoch::zero();
  epoch_request.target = tzm::ControlPlaneEpoch::first();
  const tzm::Result<tzm::EpochReceipt> epoch = engine->advance_epoch(epoch_request);
  if (!epoch.ok()) {
    std::cerr << epoch.error().to_string() << "\n";
    return 1;
  }

  tzm::ZoneConfiguration zone;
  zone.id = tzm::ZoneId::first();
  zone.name = tzm::ZoneName::literal("cpu-bay");
  zone.envelope.floor_temp = tzm::MilliCelsius{kFloorMc};
  zone.envelope.derate_onset = tzm::MilliCelsius{kDerateOnsetMc};
  zone.envelope.ceiling_temp = tzm::MilliCelsius{kCeilingMc};
  zone.envelope.critical_temp = tzm::MilliCelsius{kCriticalMc};
  zone.declared_heat = tzm::MilliWatts{kDeclaredHeatMw};
  zone.thermal_resistance = tzm::MicroKelvinPerWatt{kResistanceUkw};

  tzm::ConfigurationRequest declaration;
  declaration.command = tzm::CommandId::from_value(2);
  declaration.attempt = tzm::AttemptId::from_value(2);
  declaration.epoch = epoch.value().current;
  declaration.expected_generation = tzm::ConfigurationGeneration::zero();
  declaration.zones.push_back(zone);
  declaration.policy.coupling_hops = 1;

  const tzm::Result<tzm::ConfigurationReceipt> applied =
      engine->apply_configuration(declaration);
  if (!applied.ok()) {
    std::cerr << applied.error().to_string() << "\n";
    return 1;
  }

  const tzm::Configuration configuration = engine->configuration();
  const tzm::ZoneConfiguration* declared = configuration.find(tzm::ZoneId::first());
  if (declared == nullptr) {
    std::cerr << "the declared zone is missing from the configuration\n";
    return 1;
  }

  // The stamp must match the live generations and epoch, or the ingest is
  // refused instead of being silently downgraded.
  tzm::TemperatureObservation observation;
  observation.zone = declared->id;
  observation.zone_generation = declared->generation;
  observation.evidence_generation = configuration.evidence_generation();
  observation.sequence = tzm::ObservationSequence::first();
  observation.temperature = tzm::MilliCelsius{kObservedMc};
  observation.heat = tzm::MilliWatts{kDeclaredHeatMw};
  observation.source = tzm::SourceId::literal("synthetic-harness-01");
  observation.provenance = tzm::ProvenanceKind::SyntheticHarness;
  observation.observed_at = clock.now();
  observation.validity = tzm::Nanoseconds{kValidityNs};
  observation.publisher_epoch = epoch.value().current;
  observation.publisher_incarnation = engine->incarnation();

  const tzm::Result<tzm::ObservationReceipt> ingested = engine->ingest_observation(observation);
  if (!ingested.ok()) {
    std::cerr << ingested.error().to_string() << "\n";
    return 1;
  }

  tzm::EvaluationRequest request;
  request.id = tzm::EvaluationId::first();
  request.epoch = epoch.value().current;
  request.configuration_generation = configuration.generation();
  request.evidence_generation = configuration.evidence_generation();

  const tzm::Result<tzm::EvaluationResult> evaluated = engine->evaluate(request);
  if (!evaluated.ok()) {
    std::cerr << evaluated.error().to_string() << "\n";
    return 1;
  }

  const tzm::ZoneThermalState& state = evaluated.value().zones().front();
  const tzm::PlacementConstraint& constraint = evaluated.value().constraints().front();

  std::cout << "example 01: zone state\n";
  std::cout << "  input          : synthetic harness observation, not real hardware evidence\n";
  std::cout << "  zone           : " << tzm::to_string(state.zone) << " (" << state.name.str()
            << "), floor " << format_celsius(declared->envelope.floor_temp.value)
            << ", derate onset " << format_celsius(declared->envelope.derate_onset.value)
            << ", ceiling " << format_celsius(declared->envelope.ceiling_temp.value)
            << ", critical " << format_celsius(declared->envelope.critical_temp.value) << "\n";
  std::cout << "  observed       : " << format_celsius(state.observed_temperature.value)
            << ", provenance " << tzm::to_string(state.provenance) << "\n";
  std::cout << "  evidence       : " << tzm::to_string(state.evidence_freshness) << ", usable "
            << (tzm::is_usable(state.evidence_freshness) ? "yes" : "no") << "\n";
  std::cout << "  band           : " << tzm::to_string(state.band) << "\n";
  std::cout << "  headroom       : " << tzm::to_string(state.headroom.status) << ", proven "
            << (tzm::is_proven(state.headroom.status) ? "yes" : "no") << "\n";
  std::cout << "  temperature margin: "
            << format_celsius(state.headroom.temperature_margin.value) << "\n";
  std::cout << "  power margin   : " << format_watts(state.headroom.power_margin.value) << "\n";
  std::cout << "  constraint     : " << tzm::to_string(constraint.kind) << ", allowance "
            << (constraint.allowance_known ? format_watts(constraint.max_additional_heat.value)
                                           : std::string("not proven"))
            << "\n";
  std::cout << "  explanation    : " << constraint.explanation() << "\n";
  std::cout << "  advice only    : the constraint states an allowance for a placement planner; "
               "this runtime placed, reserved and actuated nothing\n";

  if (!tzm::is_proven(state.headroom.status) ||
      constraint.kind != tzm::PlacementConstraintKind::Bounded) {
    std::cerr << "the fresh observation did not produce a proven bounded allowance\n";
    return 1;
  }
  return 0;
}
